<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515104223 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE campagne_type_test (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, campagne_id INT NOT NULL, type_test_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B96161A16227374 ON campagne_type_test (campagne_id)');
        $this->addSql('CREATE INDEX IDX_8B96161A367C6BAC ON campagne_type_test (type_test_id)');
        $this->addSql('CREATE TABLE campagne_validation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference_campagne VARCHAR(100) NOT NULL, titre VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, statut VARCHAR(50) NOT NULL, priorite VARCHAR(20) DEFAULT NULL, date_debut_prevue TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_fin_prevue TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_debut_reelle TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin_reelle TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, commentaire_global TEXT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, responsable_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EC2780A053C59D72 ON campagne_validation (responsable_id)');
        $this->addSql('CREATE TABLE commentaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, modere BOOLEAN NOT NULL, auteur_id INT NOT NULL, campagne_id INT NOT NULL, tache_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67F068BC60BB6FE6 ON commentaire (auteur_id)');
        $this->addSql('CREATE INDEX IDX_67F068BC16227374 ON commentaire (campagne_id)');
        $this->addSql('CREATE INDEX IDX_67F068BCD2235D39 ON commentaire (tache_id)');
        $this->addSql('CREATE TABLE habilitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_notification VARCHAR(50) NOT NULL, titre VARCHAR(255) NOT NULL, message TEXT NOT NULL, canal VARCHAR(20) NOT NULL, est_lue BOOLEAN NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_lecture TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, uilisateur_id INT NOT NULL, tache_id INT DEFAULT NULL, campagne_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA961DDAA7 ON notification (uilisateur_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAD2235D39 ON notification (tache_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA16227374 ON notification (campagne_id)');
        $this->addSql('CREATE TABLE tache (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, statut VARCHAR(50) NOT NULL, priorite VARCHAR(50) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_echeance TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, campagne_id INT DEFAULT NULL, assigne_a_id INT DEFAULT NULL, createur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9387207516227374 ON tache (campagne_id)');
        $this->addSql('CREATE INDEX IDX_93872075BB1B0F33 ON tache (assigne_a_id)');
        $this->addSql('CREATE INDEX IDX_9387207573A201E5 ON tache (createur_id)');
        $this->addSql('CREATE TABLE type_test (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, fonction VARCHAR(100) DEFAULT NULL, disponibilite BOOLEAN DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, roles JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE utilisateur_habilitation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_obtention TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_expiration TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, actif BOOLEAN NOT NULL, utilisateur_id INT NOT NULL, habilitation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CE4E039BFB88E14F ON utilisateur_habilitation (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_CE4E039B389712CD ON utilisateur_habilitation (habilitation_id)');
        $this->addSql('ALTER TABLE campagne_type_test ADD CONSTRAINT FK_8B96161A16227374 FOREIGN KEY (campagne_id) REFERENCES campagne_validation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campagne_type_test ADD CONSTRAINT FK_8B96161A367C6BAC FOREIGN KEY (type_test_id) REFERENCES type_test (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campagne_validation ADD CONSTRAINT FK_EC2780A053C59D72 FOREIGN KEY (responsable_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC60BB6FE6 FOREIGN KEY (auteur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC16227374 FOREIGN KEY (campagne_id) REFERENCES campagne_validation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCD2235D39 FOREIGN KEY (tache_id) REFERENCES tache (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA961DDAA7 FOREIGN KEY (uilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAD2235D39 FOREIGN KEY (tache_id) REFERENCES tache (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA16227374 FOREIGN KEY (campagne_id) REFERENCES campagne_validation (id)');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_9387207516227374 FOREIGN KEY (campagne_id) REFERENCES campagne_validation (id)');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_93872075BB1B0F33 FOREIGN KEY (assigne_a_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE tache ADD CONSTRAINT FK_9387207573A201E5 FOREIGN KEY (createur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur_habilitation ADD CONSTRAINT FK_CE4E039BFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur_habilitation ADD CONSTRAINT FK_CE4E039B389712CD FOREIGN KEY (habilitation_id) REFERENCES habilitation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE campagne_type_test DROP CONSTRAINT FK_8B96161A16227374');
        $this->addSql('ALTER TABLE campagne_type_test DROP CONSTRAINT FK_8B96161A367C6BAC');
        $this->addSql('ALTER TABLE campagne_validation DROP CONSTRAINT FK_EC2780A053C59D72');
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BC60BB6FE6');
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BC16227374');
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BCD2235D39');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA961DDAA7');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAD2235D39');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA16227374');
        $this->addSql('ALTER TABLE tache DROP CONSTRAINT FK_9387207516227374');
        $this->addSql('ALTER TABLE tache DROP CONSTRAINT FK_93872075BB1B0F33');
        $this->addSql('ALTER TABLE tache DROP CONSTRAINT FK_9387207573A201E5');
        $this->addSql('ALTER TABLE utilisateur_habilitation DROP CONSTRAINT FK_CE4E039BFB88E14F');
        $this->addSql('ALTER TABLE utilisateur_habilitation DROP CONSTRAINT FK_CE4E039B389712CD');
        $this->addSql('DROP TABLE campagne_type_test');
        $this->addSql('DROP TABLE campagne_validation');
        $this->addSql('DROP TABLE commentaire');
        $this->addSql('DROP TABLE habilitation');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE tache');
        $this->addSql('DROP TABLE type_test');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE utilisateur_habilitation');
    }
}
